export const SHOW_PRODUCTS = "SHOW_PRODUCTS";
export const SET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SHOW_ONE_PRODUCT = "SHOW_ONE_PRODUCT";
export const SET_ISLOADING = "SET_ISLOADING";
export const DISMISS_ISLOADING = "DISMISS_ISLOADING";
